##
# Andre Pereira
# 2017-12-31
#
# Standalone compose for Jasper Server

version: '3.1'

services:
    pentaho-tools:
      build:
        context: ./
      environment:
        - XAUTH=79a9e66926cf9d965240940bca7f8fa9
        - DISPLAY=${DISPLAY}
      volumes:
        - "/tmp/.X11-unix/:/tmp/.X11-unix/:ro"
        - "./:/jobs"
        - "/home/enner/proyectos/quarein/dev/tools/prd-ce-7.1.0.0-12/report-designer/:/report-designer"